import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/components/Layout";


export const metadata: Metadata = {
  title: "Shop Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased  bg-gradient-to-b from-gray-900 via-purple-900 to-black`}
      >
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
